#контроллирует количество экземпляров подов
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2 #сколько реплик запускать
  selector:
    matchLabels: #лейблы за которыми replicaset будет следить
      # tier: frontend
      app: my-app
  template: # это уже описание пода
    metadata:
      labels:
        app: my-app
    spec:
      containers: # описание контейнеров пода
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        ports:
        - containerPort: 80
...