#запускает по 1 поду на каждой ноде кластера
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-exporter
  name: node-exporter
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: k8s.gcr.io/pause:3.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 10m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 64Mi
      nodeSelector:
        kubernetes.io/os: linux # поды будут создаваться на узлах с этой меткой
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      #tolerations - это сопротивляемость к "болезни"(taints) на ноде
      #тоесть если на ноде есть <болезнь1> то на ней не будут размещаться поды у которых нет толерантности к <болезнь1>
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ingress
      # - effect: NoSchedule
      #   operator: Exists #делаем tolerations на любой taint с указанным эффектом